name: Update Playlist

on:
  schedule:
    - cron: '*/10 * * * *' # প্রতি 10 মিনিটে
  workflow_dispatch:

permissions:
  contents: write  # repo write permission লাগবে commit করতে

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Fetch M3U8 URLs
        id: fetch
        run: |
          python fetch.py > output.log
          JSON=$(awk '/JSON_START/{flag=1;next}/JSON_END/{flag=0}flag' output.log)
          M3U=$(awk '/M3U_START/{flag=1;next}/M3U_END/{flag=0}flag' output.log)

          # Environment file ব্যবহার করে GitHub Actions step output
          echo "json<<EOF" >> $GITHUB_ENV
          echo "$JSON" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "m3u<<EOF" >> $GITHUB_ENV
          echo "$M3U" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit updated playlist
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          echo "${{ env.json }}" > playlist.json
          echo "${{ env.m3u }}" > playlist.m3u
          git add playlist.json playlist.m3u
          git diff --cached --quiet || git commit -m "Auto-update playlist $(date -u)"
          git push
