name: Update Playlist
on:
  schedule:
    - cron: '*/10 * * * *' # প্রতি ১০ মিনিটে চালাবে
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Fetch M3U8 & Update Files
        run: python fetch.py

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add playlist.json playlist.m3u
          git commit -m "Auto-update playlist"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
