name: Update Playlist

on:
  schedule:
    - cron: "*/10 * * * *"   # প্রতি 10 মিনিটে রান করবে
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python fetch.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A   # <-- সব ফাইল add করবে, না থাকলেও error হবে না
          git commit -m "Update playlist [skip ci]" || echo "No changes to commit"
          git push
