name: Update Playlist

on:
  schedule:
    - cron: '*/10 * * * *' # প্রতি 10 মিনিটে
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Fetch M3U8 URLs
        id: fetch
        run: |
          python fetch.py > output.log
          JSON=$(awk '/JSON_START/{flag=1;next}/JSON_END/{flag=0}flag' output.log)
          M3U=$(awk '/M3U_START/{flag=1;next}/M3U_END/{flag=0}flag' output.log)
          echo "::set-output name=json::$JSON"
          echo "::set-output name=m3u::$M3U"

      - name: Commit updated playlist
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          echo "${{ steps.fetch.outputs.json }}" > playlist.json
          echo "${{ steps.fetch.outputs.m3u }}" > playlist.m3u
          git add playlist.json playlist.m3u
          git commit -m "Auto-update playlist $(date -u)" || echo "No changes"
          git push
